# Generated by Django 3.1.14 on 2022-05-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap5_link', '0004_auto_20190703_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootstrap5link',
            name='link_block',
        ),
    ]
